### ISSUE TITLE
Set up dev environment for Node MCU

### ISSUE THREAD

**Issue by CollierA13j** [uah-cpe-sd-2020/dispenser#1]
Everyone that want's to develop on the Node MCU needs to set up their dev environment with the Arduino IDE, setting up git for the IDE, and any other programs we may need

**Comment by wsciaroni** [comment]
@GuassianFlux Can you attach those pictures of the environment here in a comment?

**Comment by GuassianFlux** [comment]
![DevEnv](https://user-images.githubusercontent.com/39962568/107867259-03c26a80-6e3f-11eb-9977-5aa388006729.jpg)
![DevEnv1](https://user-images.githubusercontent.com/39962568/107867262-0e7cff80-6e3f-11eb-9bdb-1a63a329cd69.jpg)
